//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Learning.EventManagement.Models
{
    using System;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.SDM;

    [SdmDomMapper]
    internal static class EventDomMapper
    {
        internal const string ModuleId = "exampleventmgmt";
        internal static DomDefinitionId DomDefinitionId = new DomDefinitionId(new Guid("b02d261b-1682-4a58-9751-93f79188fa4b"))
        {ModuleId = ModuleId};
        internal static class EventProperties
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(new Guid("379a56fe-50d1-4b07-b33d-711ffe3f7165"))
            {ModuleId = ModuleId};
            internal static FieldDescriptorID Name = new FieldDescriptorID(new Guid("1430fe85-c292-444e-b88d-1e2d78cdbad9"));
            internal static FieldDescriptorID Description = new FieldDescriptorID(new Guid("c6f21d73-eefe-4ddc-ac9e-4dfef7c40716"));
            internal static FieldDescriptorID Start = new FieldDescriptorID(new Guid("0c2b0a42-7914-478e-958d-6fc0bdbb4369"));
            internal static FieldDescriptorID End = new FieldDescriptorID(new Guid("c993bef1-2691-44f1-a264-d67ea31b6b30"));
            internal static FieldDescriptorID Type = new FieldDescriptorID(new Guid("eb067772-fc46-47ac-b41e-b6fa752878a7"));
            internal static FieldDescriptorID Status = new FieldDescriptorID(new Guid("21f92e92-33de-46a8-9e0a-a2a276d0743b"));
        }

        internal static class Languages
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(new Guid("745e8f72-5a42-4233-8b31-669fd56f8b63"))
            {ModuleId = ModuleId};
            internal static FieldDescriptorID Name = new FieldDescriptorID(new Guid("ad7abbdb-0872-4b97-9e2a-39511b03274c"));
            internal static FieldDescriptorID AudioType = new FieldDescriptorID(new Guid("400ffcb9-6bab-493a-b351-b02100a8cfae"));
            internal static FieldDescriptorID CcSupplierCompanyName = new FieldDescriptorID(new Guid("68f4209d-6f53-4375-8fd8-24442fa5b0d4"));
        }
    }
}