//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.Utils.Examples.EventManager.Models
{
    using System;
    using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
    using Skyline.DataMiner.Net.Sections;
    using Skyline.DataMiner.SDM;

    [SdmDomMapper]
    internal static class EventDomMapper
    {
        internal const string ModuleId = "exampleventmgmt";
        internal static DomDefinitionId DomDefinitionId = new DomDefinitionId(new Guid("9705e91a-ae02-4298-8329-a07b76c83ecb"))
        {ModuleId = ModuleId};
        internal static class EventProperties
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(new Guid("6f7ead6c-134a-4314-94b4-704eecd83b6a"))
            {ModuleId = ModuleId};
            internal static FieldDescriptorID Name = new FieldDescriptorID(new Guid("f32ee4e1-a6de-441d-ab86-8c79468bd587"));
            internal static FieldDescriptorID Description = new FieldDescriptorID(new Guid("34c12044-2216-48fd-9bb3-2f36d34ba2dc"));
            internal static FieldDescriptorID Start = new FieldDescriptorID(new Guid("17e71498-9388-4df4-a564-9d3b4e961d4b"));
            internal static FieldDescriptorID End = new FieldDescriptorID(new Guid("6711bbbb-1cfa-4f50-a2e7-f7a553769941"));
            internal static FieldDescriptorID Type = new FieldDescriptorID(new Guid("149ee12b-2f59-45ca-a944-f97135f2b0fc"));
            internal static FieldDescriptorID Priority = new FieldDescriptorID(new Guid("aa153d78-e013-4f88-a560-71d5c4bf337a"));
        }

        internal static class AdditionalPackages
        {
            internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(new Guid("e8916c8d-e7ce-44b4-b607-da349840f9d0"))
            {ModuleId = ModuleId};
            internal static FieldDescriptorID Type = new FieldDescriptorID(new Guid("3d0f5bc6-a3a8-4bf4-b099-41e38deef89b"));
        }
    }
}