name: Internal
permissions: write-all
on:
  push:
    branches:
    - '**'
    tags:
    - '[0-9]+.[0-9]+.[0-9]+-[0-9a-zA-Z]+'
  workflow_dispatch: 
jobs:
  CICD:
    name: CICD 
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/Internal NuGet Solution Master Workflow.yml@main
    with:
      sonarCloudProjectName: ${{ vars.SONAR_NAME }}
    secrets:
      nugetApiKey: ${{ secrets.NUGETAPIKEY_GITHUB  }}